[workspace]
members = ["internal/ruchei-sample"]

[workspace.package]
version = "0.0.41" # ad7038ef3b571dc133c108e14e6bb0f8cdcd812d and earlier have invalid versions
edition = "2021"
publish = false

[package]
name = "ruchei"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
futures-util = { version = "0.3.30", features = ["sink"] }
pin-project = "1"

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
async-tungstenite = { version = "0.24.0", features = ["async-std-runtime"] }
futures-channel = "0.3.30"
