[workspace]
members = [
    "internal/ruchei-sample",
    "ruchei-callback",
    "ruchei-extra",
    "ruchei-route",
]

[workspace.package]
edition = "2021"
publish = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/parrrate/ruchei"
authors = [
    "Alisa Feistel <alisafeistel@gmail.com>",
    "Timofey Prikhodko <tim@ongoteam.yaconnect.com>",
]
rust-version = "1.72"

[package]
name = "ruchei"
version = "0.0.94"
description = "Utilities for working with many streams"
documentation = "https://docs.rs/ruchei"
keywords = ["streams", "async", "stream"]
categories = ["asynchronous"]
readme = "README.md"
edition.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[workspace.dependencies]
ruchei-callback = { path = "ruchei-callback", version = "0.1.0" }
ruchei-extra = { path = "ruchei-extra", version = "0.1.1" }
ruchei-route = { path = "ruchei-route", version = "0.1.7", default-features = false }
ruchei-sample.path = "internal/ruchei-sample"

futures-core = "0.3.30"
futures-sink = "0.3.30"
futures-util = { version = "0.3.30", features = ["sink"] }
linked-hash-map = "0.5.6"
pin-project = "1"

[dependencies]
ruchei-callback.workspace = true
ruchei-extra.workspace = true
ruchei-route = { workspace = true, features = ["unroute"] }

futures-util.workspace = true
linked-hash-map.workspace = true
pin-project.workspace = true

[dev-dependencies]
async-io = "2.3.2"
async-net = "2.0.0"
async-std = { version = "1.12.0", features = ["attributes"] }
async-tungstenite = { version = "0.26.1" }
futures-channel = "0.3.30"
rand = "0.8.5"
thiserror = "1"
