[package]
name = "ruchei-sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
futures-util = { workspace = true, features = ["sink"] }
pin-project.workspace = true

[package.metadata.tagit]
skip = true
