[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]

[package.metadata.tagit]
skip = true
