name: Publish
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - run: echo ok
      - run: exec bin/release
        env:
          INPUT_TOKEN: ${{ secrets.PUSH_TOKEN }}
